<a href="https://colab.research.google.com/github/salav2006poudyal2025/5CS037_worksheet1_sulavpoudyal/blob/main/5CS037_worksheet1_sulavpoudyal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Empty array 2x2
arr_empty = np.empty((2,2))
print("Empty 2x2 array:\n", arr_empty)

# 2. All-one array 4x2
arr_ones = np.ones((4,2))
print("\nAll-one 4x2 array:\n", arr_ones)

# 3. Array filled with a given value
arr_full = np.full((3,3), 7)  # example fill value = 7
print("\nFull array 3x3 with value 7:\n", arr_full)

# 4. Zeros like another array
given = np.array([[1,2,3],[4,5,6]])
arr_zeros_like = np.zeros_like(given)
print("\nZeros like given array:\n", arr_zeros_like)

# 5. Ones like another array
arr_ones_like = np.ones_like(given)
print("\nOnes like given array:\n", arr_ones_like)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
np_array = np.array(new_list)
print("\nConverted list to array:", np_array)


Empty 2x2 array:
 [[3.81963606e-315 0.00000000e+000]
 [1.39067116e-309 9.50988271e-316]]

All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array 3x3 with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
 [[0 0 0]
 [0 0 0]]

Ones like given array:
 [[1 1 1]
 [1 1 1]]

Converted list to array: [1 2 3 4]


In [ ]:
# 1. Array 10 to 49
arr_range = np.arange(10, 50)
print("Array 10→49:\n", arr_range)

# 2. 3×3 matrix 0→8
matrix_3x3 = np.arange(9).reshape(3,3)
print("\n3x3 matrix 0→8:\n", matrix_3x3)

# 3. Identity matrix 3x3
identity = np.eye(3)
print("\nIdentity 3x3:\n", identity)

# 4. Random array 30 and mean
rand30 = np.random.random(30)
print("\nMean of random size-30 array:", rand30.mean())

# 5. Random 10×10 and min/max
rand10 = np.random.random((10,10))
print("\nMin:", rand10.min(), " Max:", rand10.max())

# 6. Zero array size 10, replace 5th element
z = np.zeros(10)
z[4] = 1   # 5th element index=4
print("\nZero array with 5th element = 1:\n", z)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print("\nReversed array:", rev)

# 8. 2D array with 1 border and 0 inside
border = np.ones((5,5))
border[1:-1, 1:-1] = 0
print("\nBorder 1, inside 0:\n", border)

# 9. Checkerboard 8×8
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\nCheckerboard 8x8:\n", checker)


Array 10→49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0→8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of random size-30 array: 0.4817273499199421

Min: 0.002627516524925322  Max: 0.9976273088625266

Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

Border 1, inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Addition
print("x + y:\n", x + y)

# 2. Subtraction
print("\nx - y:\n", x - y)

# 3. Multiply by integer (example: 3)
print("\n3 * x:\n", 3 * x)

# 4. Square elements
print("\nx squared:\n", x**2)

# 5. Dot products
print("\nv·w =", np.dot(v,w))
print("x·v =", np.dot(x, v))
print("x·y =\n", np.dot(x, y))

# 6. Concatenate along rows and columns
row_concat = np.vstack((x, y))
col_concat = np.column_stack((v, w))
print("\nRow concat x & y:\n", row_concat)
print("\nColumn concat v & w:\n", col_concat)

# 7. Concatenate x and v → why error?
try:
    np.concatenate((x, v))
except Exception as e:
    print("\nError when concatenating x and v:")
    print(e)
    print("\nExplanation: x is 2D (2×2) but v is 1D (size 2), so shapes do not match.")


x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

3 * x:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

v·w = 219
x·v = [29 77]
x·y =
 [[19 22]
 [50 58]]

Row concat x & y:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Column concat v & w:
 [[ 9 11]
 [10 12]]

Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: x is 2D (2×2) but v is 1D (size 2), so shapes do not match.


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 =\n", I)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB equals BA? →", np.allclose(AB, BA))

# 3. (AB)^T = B^T A^T
lhs = (AB).T
rhs = np.dot(B.T, A.T)
print("\n(AB)^T =\n", lhs)
print("B^T A^T =\n", rhs)
print("Equal? →", np.allclose(lhs, rhs))


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB equals BA? → False

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Equal? → True


In [ ]:
A = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

B = np.array([-1, -3, 9])


In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using inverse:\n", X)


Solution using inverse:
 [ 2.  1. -2.]
